---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: templates
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  path: ./opa/templates
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  dependsOn:
    - name: templates
  interval: 5m
  path: "./opa/policies"
  prune: true
  sourceRef:
    kind: GitRepositorys
    name: flux-system